version: "3.7"

volumes:
  dbdata:

services:

  php-fpm:
    build: ./
    ports:
      - 5000:8000
    volumes:
      - ./:/var/www/html

  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: moon
      MYSQL_ROOT_PASSWORD: root
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 6033:3306
    volumes:
      - dbdata:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8000:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
  node:
    image: node:current-alpine3.12
    ports:
      - 3000:3000
    volumes:
      - ./:/var/www/html
